settings:
  name: "NetApp Virtualization solutions"
  rss_page: "/whats-new.html"
  internal:
    pdf_enabled: false
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    lipi_enabled: true
  pdf: 
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions-virtualization.zip

product-family:
  name: NetApp Solutions
  repo: netapp-solutions-family

sidebar:
  entries:
    - title: "Virtualization solutions"
      url: /index.html
    - title: "What's new"
      url: /whats-new.html
    - section: vmw-sc
    - section: virtualization
    - section: containers
#
    - title: "Videos"
      url: /video-landing-page/index.html
      entries:
        - title: "OpenShift virtualization"
          url: /openshift-videos.html
        - title: "VMware virtualization"
          url: /vmware-videos.html
        - title: "Hybrid multicloud virtualization"
          url: /hybrid-cloud-videos.html
    - title: "Blogs"
      url: /blogs.html
    - title: "Change Log"
      url: /whats-new.html
    - title: "Legal notices"
      url: /legal-notices.html
