settings:
  name: "NetApp virtualization solutions"
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    lipi_enabled: true
  pdf: 
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions-virtualization.zip

product-family:
  name: NetApp solutions
  repo: netapp-solutions-family

sidebar:
  entries:
    - title: "Virtualization solutions"
      url: /index.html
    - title: "What's new"
      url: /whats-new.html
    - section: virtualization
    - section: vmware
    - section: hyperv
    - section: osv
    - section: proxmox
    - section: kvm
    - section: migration
#
    - title: "Videos"
      url: /videos/index.html
      entries:
        - title: "OpenShift virtualization"
          url: /openshift-videos.html
        - title: "VMware virtualization"
          url: /vmware-videos.html
        - title: "Hybrid multicloud virtualization"
          url: /hybrid-cloud-videos.html
    - title: "Blogs"
      url: /blogs.html
    - title: "Legal notices"
      url: /legal-notices.html
