---
sidebar: sidebar
permalink: videos.html
summary: Series of videos and demos discussing the features of many of NetApp's solutions
keywords: netapp, solutions, videos, demos
---

= NetApp Solutions: Videos and Demos
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Overview of the videos and demos highlighting specific features of many of NetApp's solutions.

== Enterprise Applications and Databases
[underline]#*Videos for open source databases*#

video::c381b887-8c8b-4d7d-8b0f-b0c0010c5c04[panopto, title="PostgreSQL automated deployment, HA/DR replication setup, failover, resync", width=360]

[underline]#*Videos for Oracle database*#

video::74062c18-b120-45b7-9bf9-b2db00f73675[panopto, title="Automated Oracle DB clone from DataGuard standby on GCNV with ASM", width=360]

video::960fb370-c6e0-4406-b6d5-b110014130e8[panopto, title="Oracle Database Backup, Recovery, and Clone on ANF with SnapCenter", width=360]

video::d1c859b6-e45a-44c7-8361-b10f012fc89b[panopto, title="Simplified and automated Oracle deployment on Azure NetApp Files with NFS", width=360]

video::81e389a0-d9b8-495c-883b-b0d701710847[panopto, title="Simplified and automated Oracle deployment on Amazon FSx ONTAP with iSCSI", width=360]

video::79095731-6b02-41d5-9fa1-b0c00100d055[panopto, title="Simplified and automated Oracle deployment on NetApp ASA with iSCSI", width=360]

video::b1a7bb05-caea-44a0-bd9a-b01200f372e9[panopto, title="Part 1 - Oracle modernization with hybrid cloud in AWS and FSx ONTAP", width=360]

video::bb088a3e-bbfb-4927-bf44-b01200f38b17[panopto, title="Part 2a - Database migration from on-premises to AWS using automated PDB relocation with maximum availability", width=360]

video::c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8[panopto, title="Part 2b - Database migration from on-premises to AWS using BlueXP console via SnapMirror", width=360]

video::5fd03759-a691-4007-9748-b01200f3b79c[panopto, title="Part 3 - Automated database HA/DR replication setup, failover, resync",width=360]

video::2f731d7c-0873-4a4d-8491-b01200f90a82[panopto, title="Part 4a - Database clone for Dev/Test with SnapCenter UI from replicated standby copy", width=360]
 
video::97790d62-ff19-40e0-9784-b01200f920ed[panopto, title="Part 4b - Database backup, restore, clone with SnapCenter UI", width=360]

video::4b0fd212-7641-46b8-9e55-b01200f9383a[panopto, title="Part 4c - Database backup, restore with BlueXP SaaS Apps backup and recovery", width=360]

[underline]#*Videos for SQL Server database*#

video::27f28284-433d-4273-8748-b01200fb3cd7[panopto, title="Deploy SQL Server on AWS EC2 using Amazon FSx ONTAP", width=360]

video::krzMWjrrMb0[youtube, title="Oracle Multi-Tenant Pluggable Database Clone Using Storage Snapshots", width=360]
 
video::VcQMJIRzhoY[youtube, title="Automated Oracle 19c RAC Deployment on FlexPod with Ansible", width=360]

*Case Study*

* link:https://customers.netapp.com/en/sap-azure-netapp-files-case-study[SAP on Azure NetApp Files^]


== Hybrid MultiCloud with Red Hat OpenShift 

video::36ecf505-5d1d-4e99-a6f8-b11c00341793[panopto, title="Snapshot/Restore for Applications on Red Hat OpenShift Service on AWS (ROSA)clusters with Amazon FSx ONTAP storage",width=360]

video::621ae20d-7567-4bbf-809d-b01200fa7a68[panopto, title="Integration of FSx ONTAP with Trident", width=360]

video::e9a07d79-42a1-4480-86be-b01200fa62f5[panopto, title="Failover and Fail-back of apps on ROSA with FSx ONTAP", width=360]

== Virtualization
* link:vmware/vmw-demos-videos.html[VMware Video Collection]

== Containers / Kubernetes

* link:https://docs.netapp.com/us-en/netapp-solutions-containers/anthos/anthos-videos-and-demos.html[NetApp with Google Anthos Videos^]
* link:https://docs.netapp.com/us-en/netapp-solutions-containers/tanzu/vtwn-videos-and-demos.html[NetApp with VMware Tanzu Videos^]
* link:openshift/os-videos-and-demos.html[NetApp with Red Hat OpenShift Videos]
