---
sidebar: sidebar
permalink: vmware/vmw-getting-started-snapcenter.html
keywords: netapp, vmware, getting, started
summary:
---

= Learn about backup and restore of virtual machines using SnapCenter plug-in for VMware vSphere
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The SnapCenter Plug-in for VMware vSphere enables fast, VM-consistent backup and restore operations for VMs, datastores, and VMDK files. This VMware plug-in integrates with SnapCenter Server to support application-based backup and restore for SnapCenter application-specific plug-ins. 

== Documentation resources

Refer to the following documentation resources for detailed information.

* link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/[SnapCenter Plug-in for VMware vSphere documentation]

== Solution resources

Refer to the following 3-2-1 backup solution featuring SnapCenter Plug-in for VMware vSphere and BlueXP backup and recovery for VMs.

Technical Report: link:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-321-dp-scv.html[3-2-1 Data Protection for VMware with SnapCenter Plug-in and BlueXP backup and recovery for VMs^]

Tech ONTAP Blog: link:https://community.netapp.com/t5/Tech-ONTAP-Blogs/3-2-1-Data-Protection-for-VMware-with-SnapCenter-Plug-in-and-BlueXP-backup-and/ba-p/446180[3-2-1 Data Protection for VMware with SnapCenter Plug-in and BlueXP backup and recovery for VMs]

== Video resources

video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto, title="SnapCenter Plug-in for VMware vSphere - Solution Pre-Requisites"]

video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto, title="SnapCenter Plug-in for VMware vSphere - Deployment"]

video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto, title="SnapCenter Plug-in for VMware vSphere - Backup Workflow"]

video::ed41002e-585c-445d-a60c-b01200fb1188[panopto, title="SnapCenter Plug-in for VMware vSphere - Restore Workflow"]

video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto, title="SnapCenter - SQL Restore Workflow"]