---
sidebar: sidebar
permalink: vmware/vmw-getting-started-dii.html
keywords: vmware, getting, started, overview, netapp, data, infrastructure, insights, dii
summary: 
---

= Learn about monitoring a complete infrastructure using NetApp Data Infrastructure Insights
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp Data Infrastructure Insights (formerly Cloud Insights) monitors on-premises and cloud systems, offering visibility into your complete IT environment, including VMware vSphere and ONTAP storage systems. It enables capabilities such as performance tracking, issue detection, and resource optimization across your public and private environments.

== Introduction

With Data Infrastructure Insights, you can monitor, troubleshoot and optimize all your resources including your public clouds and your private data centers.

For more information on Data Infrastructure Insights, see link:https://docs.netapp.com/us-en/data-infrastructure-insights/index.html[Data Infrastructure Insights Documentation].

== Data Infrastructure Insights Capabilities

* Data Infrastructure Insights provides hybrid multicloud monitoring, giving you full-stack observability of infrastructure and workloads.
* Data collectors for heterogeneous infrastructure and workloads, including Kubernetes
* Open Telegraf collector and open APIs for easy integration
* Comprehensive alerting and notifications
* Machine learning for intelligent insights
* Optimize resource utilization
* Built-in or customizable dashboards with advanced filters to minimize display noise to answer questions
* Discover the health of your ONTAP storage operations 
* Protect your most valuable business asset – data - from ransomware or data destruction attack

// NetApp Solutions restructuring (jul 2025) - renamed from vmware/vmw-getting-started-data-infrastructure-insights.adoc
