---
sidebar: sidebar
permalink: vmware/vmw-vcf-deployment.html
keywords: netapp, vmware, cloud, foundation, vcf, flexpod
summary:
---

== Deployment of Private Cloud with VMware Cloud Foundation and ONTAP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
There are various ways to setup VCF 9 environment with ONTAP depending on their current state. The option includes deployment, converge and upgrade. This document explore those options with specific guidelines for ONTAP.

Principal Storage options available for VCF with ONTAP:

[cols="4,2,2" options="header"]
|===
// header row
| Product Family
| VMFS on FC
| NFSv3


| ASA A-Series and C-Series
| Yes
| No


| AFF A-Series and C-Series
| Yes
| Yes

| FAS
| Yes
| Yes

// table end
|===

Supplemental Storage options available for VCF with ONTAP:

[cols="4,2,2,2,2,2" options="header"]
|===
// header row
| Product Family
| VMFS on FC
| VMFS on iSCSI
| VMFS on NVMe-oF
| NFSv3
| NFSv4.1


| ASA A-Series and C-Series
| Yes
| Yes
| Yes
| No
| No


| AFF A-Series and C-Series
| Yes
| Yes
| Yes
| Yes
| Yes

| FAS
| Yes
| Yes
| Yes
| Yes
| Yes

// table end
|===

=== Deploying a new VCF Instance with version 9.0
Customers choose this option to setup a fresh installation of VCF 9 and later they plan to migrate to this environment or start consuming by deploying applications or provide infrastructure services to their clients.

For high level steps, check link:https://techdocs.broadcom.com/content/dam/broadcom/techdocs/us/en/assets/vmware-cis/vcf/vcf-9.0-vcf-deploy-journey.pdf[Build Journey - Install a new VMware Cloud Foundation Deployment]

Follow link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-0/deployment/deploying-a-new-vmware-cloud-foundation-or-vmware-vsphere-foundation-private-cloud-/preparing-your-environment.html[Broadcom VCF 9 deployment steps]

In Deployment Preparation step, based on the Principal Storage option, complete the following steps

.VMFS on FC
[%collapsible%]
====
. Gather WWPN of all ESX hosts. We used 'esxcli storage san fc list' from host cli. WWPN can also read from ESX web interface or using PowerCLI.
. Complete Zoning configuration. Refer link:https://docs.netapp.com/us-en/ontap/san-config/fc-fcoe-recommended-zoning-configuration.html#dual-fabric-zoning-configurations[Recommended FC Zoning configurations for ONTAP Systems]. 
+
NOTE: Need to use WWPN of Logical Interfaces of SVM rather than Physical interface.
. Create LUN and present that LUN to hosts defined using WWPN using System Manager or ONTAP CLI or API.
. Rescan the storage adapter on ESX and Create VMFS Datastore.
====

.NFSv3
[%collapsible%]
====
. Create VMKernel interface on one of the ESX host.
. Ensure link:https://docs.netapp.com/us-en/ontap/task_nas_enable_linux_nfs.html[SVM is available with NFS protocol] and link:https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-vmware-vstorage-over-nfs-task.html[vstorage enabled].
. Create Volume and Export with policy allowing ESX hosts.
. Adjust permissions based on requirements.
. Deploy ONTAP NFS VAAI vib on ESX host to include it as part of vLCM image. We used the command 'esxcli software vib install -d /NetAppNasPlugin2.0.1.zip'. The NFS VAAI zip file can be downloaded from NetApp Support Site.
. Mount NFS volume on same host where VMKernel interface defined. We used the command 'esxcli storage nfs add -c 4 -H 192.168.122.210  -s /use1_m01_nfs01 -v use1-m01-cl01-nfs01'
+
NOTE: Currently the nConnect option doesn't apply to other hosts. Need to update the nConnect session number for other hosts on post deployment.
====

In Deploy VCF Fleet phase at end of Verify deployment summary and review next steps, include

.ONTAP tools deployment
[%collapsible%]
====
. link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html[Download ONTAP tools 10.x version from NetApp Support Site].
. Register DNS entries for ONTAP tools Manager, node(s) and virtual IP for internal communication.
. Deploy the OVA to Management vCenter server.
. link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html[Register Management Domain vCenter to ONTAP tools Manager].
. link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html[Add Storage backend with vSphere client user interface].
. link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-datastore.html[Create Supplemental Datastore (Include one for Content Registry)].
. Create Content Registry if HA deployment is planned.
. link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/manage/edit-appliance-settings.html[From ONTAP tools Manager, enable HA]

====

.SnapCenter Plugin for VMware vSphere deployment
[%collapsible%]
====
. link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere_01.html[Deploy SnapCenter Plug-in for VMware vSphere]
. link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_add_storage.html[Add Storage backend]
. link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_backup_policies.html[Create backup policies]
. link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_resource_groups.html[Create Resource Groups]

====

.BlueXP Connector deployment
[%collapsible%]
====
. link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#what-you-can-do-without-a-connector[Learn about BlueXP Connector]
. link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html#overview[Connector deployment]

====

.BlueXP Backup and Recovery Configuration
[%collapsible%]
====
. link:https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-vmware-protect-overview.html[VM Workloads]
. link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-kubernetes-protect-overview.html[VKS Workloads]

====

In Import vCenters phase, at end of import vCenter as workload domain in the VCF instance, include

.ONTAP tools registration
[%collapsible%]
====
. link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html[Register Workload domain vCenter to ONTAP tools Manager].
. link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html[Add Storage backend with vSphere client user interface].
. link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-datastore.html[Create Supplemental Datastore].
====

.SnapCenter Plugin for VMware vSphere deployment
[%collapsible%]
====
. link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere_01.html[Deploy SnapCenter Plug-in for VMware vSphere]
. link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_add_storage.html[Add Storage backend]
. link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_backup_policies.html[Create backup policies]
. link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_resource_groups.html[Create Resource Groups]

====

.BlueXP Backup and Recovery Configuration
[%collapsible%]
====
. link:https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-vmware-protect-overview.html[VM Workloads]
. link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-kubernetes-protect-overview.html[VKS Workloads]

====

The above steps also valid whenever new workload domain is created.

=== Converging existing components to VCF 9.0
Customers often have some of the components of VCF fleet already and they prefer to reuse it. Here is the link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-0/deployment/converging-your-existing-vsphere-infrastructure-to-a-vcf-or-vvf-platform-/supported-scenarios-to-converge-to-vcf.html[supported scenarios to Converge to VCF]

While reusing a vCenter Instance, the Datastores are often provisioned with ONTAP tools and it can be used as Principal Storage for VCF.

Follow link:https://imt.netapp.com/imt/#welcome[Interoperability Matrix Tool] to link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/upgrade/upgrade-ontap-tools.html[upgrade ONTAP tools] and link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_upgrade.html[SnapCenter Plugin for VMware vSphere] that is supported for VCF 9.

=== Upgrading existing VCF environment to 9.0
Customers already on VCF environment can upgrade to VCF 9.0 using typical upgrade process. Refer link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-0/deployment/upgrading-cloud-foundation.html[Upgrade VCF Management Domain to VCF 9] and link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-0/lifecycle-management/lifecycle-management-of-vcf-core-components/upgrade-workload-domains-to-vcf-5-2.html[Upgrade VCF 5.x Workload Domain to VCF 9]

Follow link:https://imt.netapp.com/imt/#welcome[Interoperability Matrix Tool] to link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/upgrade/upgrade-ontap-tools.html[upgrade ONTAP tools] and link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_upgrade.html[SnapCenter Plugin for VMware vSphere] that is supported for VCF 9.