---
sidebar: sidebar
permalink: vmware/vmw-vcf-expand.html
keywords: vmware, vcf, expand, supplemental, storage
summary: 
---
= Learn about expanding storage for a VCF environment using supplemental storage
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
VMware Cloud Foundation (VCF) supports a wide range of supplemental storage options to expand storage on VCF management domains and Virtual Infrastructure (VI) workload domains.

NetApp's ONTAP Tools for VMware vSphere provide an efficient solution for this expansion by integrating NetApp storage seamlessly into the VCF environment. ONTAP Tools simplify the setup and management of datastores, allowing administrators to provision and manage storage directly from the vSphere Client. ONTAP's advanced features such as snapshots, cloning, and data protection, enhancing storage performance, efficiency, and scalability within the VCF environment.

Please refer to the following solutions for the technical details to expand the VCF environment.

* link:vmw-vcf-mgmt-supplemental-iscsi.html[Management Domain with iSCSI]

* link:vmw-vcf-mgmt-supplemental-fc.html[Management Domain with FC]

* link:vmw-vcf-viwld-supp-iscsi-vvols.html[Virtual Infrastructure Workload Domain with vVols (iSCSI)]

* link:vmw-vcf-viwld-supp-nfs-vvols.html[Virtual Infrastructure Workload Domain with vVols (NFS)]

* link:vmw-vcf-viwld-supp-nvme.html[Virtual Infrastructure Workload Domain with NVMe/TCP]

* link:vmw-vcf-viwld-supp-fc.html[Virtual Infrastructure Workload Domain with FC]
