---
sidebar: sidebar
permalink: openshift/os-ci-integration.html
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, OpenShift Virtualization, CNV, Container Native Virtualization, Red Hat OpenShift Virtualization, cloud Insights
summary: Monitoring using Cloud Insights for VMs in Red Hat OpenShift Virtualization 
---

= Integrate Data Infrastructure Insights to collect VM data in Red Hat OpenShift Virtualization
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
To start collecting data for VMs in OpenShift Virtualization, you need to install several components, including a Kubernetes monitoring operator, a data collector for Kubernetes, and an acquisition unit to gather data from ONTAP storage supporting VM disks.

. A Kubernetes monitoring operator and data collector to collect Kubernetes data
For complete instructions, refer to the link:https://docs.netapp.com/us-en/cloudinsights/task_config_telegraf_agent_k8s.html[documentation].

. An acquisition unit to collect data from ONTAP storage that provides persistent storage for the VM disks
For complete instructions, refer to the link:https://docs.netapp.com/us-en/cloudinsights/task_getting_started_with_cloud_insights.html[documentation].

. A data collector for ONTAP
For complete instructions, refer to the link:https://docs.netapp.com/us-en/cloudinsights/task_getting_started_with_cloud_insights.html#configure-the-data-collector-infrastructure[documentation]

Additionally, if you are using StorageGrid for VM backups, you need a data collector for the StorageGRID as well.


// NetApp Solutions restructuring (jul 2025) - renamed from containers/rh-os-n_use_case_openshift_virtualization_ci_integration.adoc
