---
sidebar: sidebar
permalink: openshift/osv-vm-dp-delete-using-velero.html
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, OpenShift Virtualization, CNV, Container Native Virtualization, Red Hat OpenShift Virtualization, OADP operator, Openshift Data Protection Application operator, velero
summary: Red Hat OpenShift Virtualization with NetApp ONTAP
---
= Delete a backup CR or restore CR in Red Hat OpenShift Virtualization using Velero
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Delete backup and restore resources for VMs in OpenShift Virtualization using Velero. Use the OpenShift CLI to delete backups while retaining object storage data, or the Velero CLI to delete both the Backup Custom Resource (CR) and associated storage data.

== Deleting a backup

You can delete a Backup CR without deleting the Object Storage data by using the OC CLI tool.
....
oc delete backup <backup_CR_name> -n <velero_namespace>
....

If you want the delete the Backup CR and delete the associated object storage data, you can do so by using the Velero CLI tool.

Download the CLI as given in the instructions in the link:https://velero.io/docs/v1.3.0/basic-install/#install-the-cli[Velero documentation].

Execute the following delete command using the Velero CLI
....
velero backup delete <backup_CR_name> -n <velero_namespace>
....

== Deleting a Restore
You can delete the Restore CR using the Velero CLI
....
velero restore delete restore --namespace openshift-adp
....

You can use oc command as well as the UI to delete the restore CR
....
oc delete backup <backup_CR_name> -n <velero_namespace>
....

// NetApp Solutions restructuring (jul 2025) - renamed from containers/rh-os-n_use_case_openshift_virtualization_dataprotection_delete.adoc
